program ThsERP;

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  Winapi.Messages,
  Vcl.Styles.Utils.SystemMenu in 'BackEnd\Tools\Vcl.Styles.Utils.SystemMenu.pas',
  Ths.Erp.Database in 'BackEnd\Ths.Erp.Database.pas',
  Ths.Erp.Database.Singleton in 'BackEnd\Ths.Erp.Database.Singleton.pas',
  Ths.Erp.Database.Connection.Settings in 'BackEnd\Ths.Erp.Database.Connection.Settings.pas',
  Ths.Erp.Database.Table in 'BackEnd\Ths.Erp.Database.Table.pas',
  Ths.Erp.Database.Table.Ulke in 'BackEnd\Ths.Erp.Database.Table.Ulke.pas',
  Ths.Erp.Database.Table.Employee in 'BackEnd\Ths.Erp.Database.Table.Employee.pas',
  Ths.Erp.Database.Table.SysUserAccessRight in 'BackEnd\Ths.Erp.Database.Table.SysUserAccessRight.pas',
  Ths.Erp.Database.Table.SysGridColWidth in 'BackEnd\Ths.Erp.Database.Table.SysGridColWidth.pas',
  mORMotReport in 'BackEnd\synpdf\mORMotReport.pas',
  SynCommons in 'BackEnd\synpdf\SynCommons.pas',
  SynCrypto in 'BackEnd\synpdf\SynCrypto.pas',
  SynGdiPlus in 'BackEnd\synpdf\SynGdiPlus.pas',
  SynLZ in 'BackEnd\synpdf\SynLZ.pas',
  SynPdf in 'BackEnd\synpdf\SynPdf.pas',
  SynZip in 'BackEnd\synpdf\SynZip.pas',
  ufrmBase in 'Forms\ufrmBase.pas' {frmBase},
  ufrmBaseOutput in 'Forms\OutputForms\Factory\ufrmBaseOutput.pas' {frmBaseOutput},
  ufrmBaseStrGrid in 'Forms\OutputForms\StrGrid\Factory\ufrmBaseStrGrid.pas' {frmBaseStrGrid},
  ufrmBaseDBGrid in 'Forms\OutputForms\DbGrid\Factory\ufrmBaseDBGrid.pas' {frmBaseDBGrid},
  ufrmBaseInputDB in 'Forms\InputForms\Factory\ufrmBaseInputDB.pas' {frmBaseInputDB},
  ufrmMain in 'Forms\InputForms\ufrmMain.pas' {frmMain},
  ufrmLogin in 'Forms\InputForms\ufrmLogin.pas' {frmLogin},
  Ths.Erp.Database.Table.SysUser in 'BackEnd\Ths.Erp.Database.Table.SysUser.pas',
  Ths.Erp.SpecialFunctions in 'BackEnd\Ths.Erp.SpecialFunctions.pas',
  ufrmUlkeler in 'Forms\OutputForms\DbGrid\ufrmUlkeler.pas' {frmUlkeler},
  ufrmUlke in 'Forms\InputForms\ufrmUlke.pas' {frmUlke},
  Ths.Erp.Constants in 'BackEnd\Ths.Erp.Constants.pas',
  ufrmSehir in 'Forms\InputForms\ufrmSehir.pas' {frmSehir},
  ufrmAbout in 'Forms\ufrmAbout.pas' {frmAbout},
  Ths.Erp.Database.Table.Field in 'BackEnd\Ths.Erp.Database.Table.Field.pas',
  Ths.Erp.Database.Table.Sehir in 'BackEnd\Ths.Erp.Database.Table.Sehir.pas',
  ufrmSehirler in 'Forms\OutputForms\DbGrid\ufrmSehirler.pas' {frmSehirler},
  ufrmFilterDBGrid in 'Forms\InputForms\ufrmFilterDBGrid.pas' {frmFilterDBGrid},
  ufrmSysPermissionSourceGroups in 'Forms\OutputForms\DbGrid\ufrmSysPermissionSourceGroups.pas' {frmSysPermissionSourceGroups},
  Ths.Erp.Database.Table.SysPermissionSource in 'BackEnd\Ths.Erp.Database.Table.SysPermissionSource.pas',
  ufrmSysPermissionSourceGroup in 'Forms\InputForms\ufrmSysPermissionSourceGroup.pas' {frmSysPermissionSourceGroup},
  ufrmSysPermissionSources in 'Forms\OutputForms\DbGrid\ufrmSysPermissionSources.pas' {frmSysPermissionSources},
  ufrmSysPermissionSource in 'Forms\InputForms\ufrmSysPermissionSource.pas' {frmSysPermissionSource},
  Ths.Erp.Database.Table.SysPermissionSourceGroup in 'BackEnd\Ths.Erp.Database.Table.SysPermissionSourceGroup.pas',
  Ths.Erp.Database.Table.SysLang in 'BackEnd\Ths.Erp.Database.Table.SysLang.pas',
  Ths.Erp.Database.Table.SysLangGuiContent in 'BackEnd\Ths.Erp.Database.Table.SysLangGuiContent.pas',
  ufrmSysUserAccessRights in 'Forms\OutputForms\DbGrid\ufrmSysUserAccessRights.pas' {frmSysUserAccessRights},
  ufrmSysUserAccessRight in 'Forms\InputForms\ufrmSysUserAccessRight.pas' {frmSysUserAccessRight},
  Ths.Erp.Database.Table.SysGridColColor in 'BackEnd\Ths.Erp.Database.Table.SysGridColColor.pas',
  Ths.Erp.Database.Table.SysGridColPercent in 'BackEnd\Ths.Erp.Database.Table.SysGridColPercent.pas',
  Ths.Erp.Database.Table.View.SysViewColumns in 'BackEnd\Ths.Erp.Database.Table.View.SysViewColumns.pas',
  Ths.Erp.Database.Table.View in 'BackEnd\Ths.Erp.Database.Table.View.pas',
  ufrmSysLangs in 'Forms\OutputForms\DbGrid\ufrmSysLangs.pas' {frmSysLangs},
  ufrmSysLang in 'Forms\InputForms\ufrmSysLang.pas' {frmSysLang},
  ufrmSysGridColWidth in 'Forms\InputForms\ufrmSysGridColWidth.pas' {frmSysGridColWidth},
  ufrmSysGridColWidths in 'Forms\OutputForms\DbGrid\ufrmSysGridColWidths.pas' {frmSysGridColWidths},
  ufrmSysGridColColor in 'Forms\InputForms\ufrmSysGridColColor.pas' {frmSysGridColColor},
  ufrmSysGridColPercent in 'Forms\InputForms\ufrmSysGridColPercent.pas' {frmSysGridColPercent},
  ufrmSysGridColColors in 'Forms\OutputForms\DbGrid\ufrmSysGridColColors.pas' {frmSysGridColColors},
  ufrmSysGridColPercents in 'Forms\OutputForms\DbGrid\ufrmSysGridColPercents.pas' {frmSysGridColPercents},
  Ths.Erp.Database.Table.AyarHaneSayisi in 'BackEnd\Ths.Erp.Database.Table.AyarHaneSayisi.pas',
  Ths.Erp.Database.Table.ParaBirimi in 'BackEnd\Ths.Erp.Database.Table.ParaBirimi.pas',
  ufrmParaBirimi in 'Forms\InputForms\ufrmParaBirimi.pas' {frmParaBirimi},
  ufrmParaBirimleri in 'Forms\OutputForms\DbGrid\ufrmParaBirimleri.pas' {frmParaBirimleri},
  ufrmSysLangGuiContents in 'Forms\OutputForms\DbGrid\ufrmSysLangGuiContents.pas' {frmSysLangGuiContents},
  ufrmSysLangGuiContent in 'Forms\InputForms\ufrmSysLangGuiContent.pas' {frmSysLangGuiContent},
  Ths.Erp.Database.Table.SysLangDataContent in 'BackEnd\Ths.Erp.Database.Table.SysLangDataContent.pas',
  ufrmSysLangDataContents in 'Forms\OutputForms\DbGrid\ufrmSysLangDataContents.pas' {frmSysLangDataContents},
  ufrmSysLangDataContent in 'Forms\InputForms\ufrmSysLangDataContent.pas' {frmSysLangDataContent},
  Ths.Erp.Database.Table.SysQualityFormNumber in 'BackEnd\Ths.Erp.Database.Table.SysQualityFormNumber.pas',
  ufrmSysQualityFormNumbers in 'Forms\OutputForms\DbGrid\ufrmSysQualityFormNumbers.pas' {frmSysQualityFormNumbers},
  ufrmSysQualityFormNumber in 'Forms\InputForms\ufrmSysQualityFormNumber.pas' {frmSysQualityFormNumber},
  Ths.Erp.Database.Table.AyarStokHareketTipi in 'BackEnd\Ths.Erp.Database.Table.AyarStokHareketTipi.pas',
  ufrmAyarStokHareketTipleri in 'Forms\OutputForms\DbGrid\ufrmAyarStokHareketTipleri.pas' {frmAyarStokHareketTipleri},
  ufrmAyarStokHareketTipi in 'Forms\InputForms\ufrmAyarStokHareketTipi.pas' {frmAyarStokHareketTipi},
  Ths.Erp.Database.Table.StokHareketi in 'BackEnd\Ths.Erp.Database.Table.StokHareketi.pas',
  ufrmStokHareketleri in 'Forms\OutputForms\DbGrid\ufrmStokHareketleri.pas' {frmStokHareketleri},
  ufrmStokHareketi in 'Forms\InputForms\ufrmStokHareketi.pas' {frmStokHareketi},
  Ths.Erp.Database.Table.SysGridDefaultOrderFilter in 'BackEnd\Ths.Erp.Database.Table.SysGridDefaultOrderFilter.pas',
  ufrmSysGridDefaultOrderFilters in 'Forms\OutputForms\DbGrid\ufrmSysGridDefaultOrderFilters.pas' {frmSysGridDefaultOrderFilters},
  ufrmSysGridDefaultOrderFilter in 'Forms\InputForms\ufrmSysGridDefaultOrderFilter.pas' {frmSysGridDefaultOrderFilter},
  Ths.Erp.Database.Table.AyarEFaturaFaturaTipi in 'BackEnd\Ths.Erp.Database.Table.AyarEFaturaFaturaTipi.pas',
  ufrmAyarEFaturaFaturaTipleri in 'Forms\OutputForms\DbGrid\ufrmAyarEFaturaFaturaTipleri.pas' {frmAyarEFaturaFaturaTipleri},
  ufrmAyarEFaturaFaturaTipi in 'Forms\InputForms\ufrmAyarEFaturaFaturaTipi.pas' {frmAyarEFaturaFaturaTipi},
  Ths.Erp.Database.Table.AyarFirmaTipi in 'BackEnd\Ths.Erp.Database.Table.AyarFirmaTipi.pas',
  ufrmAyarFirmaTipleri in 'Forms\OutputForms\DbGrid\ufrmAyarFirmaTipleri.pas' {frmAyarFirmaTipleri},
  ufrmAyarFirmaTipi in 'Forms\InputForms\ufrmAyarFirmaTipi.pas' {frmAyarFirmaTipi},
  Ths.Erp.Database.Table.AyarEFaturaIletisimKanali in 'BackEnd\Ths.Erp.Database.Table.AyarEFaturaIletisimKanali.pas',
  ufrmAyarEFaturaIletisimKanallari in 'Forms\OutputForms\DbGrid\ufrmAyarEFaturaIletisimKanallari.pas' {frmAyarEFaturaIletisimKanallari},
  ufrmAyarEFaturaIletisimKanali in 'Forms\InputForms\ufrmAyarEFaturaIletisimKanali.pas' {frmAyarEFaturaIletisimKanali},
  Ths.Erp.Database.Table.AyarEFaturaIstisnaKodu in 'BackEnd\Ths.Erp.Database.Table.AyarEFaturaIstisnaKodu.pas',
  ufrmAyarEFaturaIstisnaKodlari in 'Forms\OutputForms\DbGrid\ufrmAyarEFaturaIstisnaKodlari.pas' {frmAyarEFaturaIstisnaKodlari},
  ufrmAyarEFaturaIstisnaKodu in 'Forms\InputForms\ufrmAyarEFaturaIstisnaKodu.pas' {frmAyarEFaturaIstisnaKodu},
  Ths.Erp.Database.Table.SysApplicationSettings in 'BackEnd\Ths.Erp.Database.Table.SysApplicationSettings.pas',
  ufrmSysApplicationSetting in 'Forms\InputForms\ufrmSysApplicationSetting.pas' {frmSysApplicationSetting},
  Ths.Erp.Database.Table.SysApplicationSettingsOther in 'BackEnd\Ths.Erp.Database.Table.SysApplicationSettingsOther.pas',
  ufrmSysApplicationSettingsOther in 'Forms\InputForms\ufrmSysApplicationSettingsOther.pas' {frmSysApplicationSettingsOther},
  Ths.Erp.Database.Table.PersonelBilgisi in 'BackEnd\Ths.Erp.Database.Table.PersonelBilgisi.pas',
  ufrmPersonelBilgileri in 'Forms\OutputForms\DbGrid\ufrmPersonelBilgileri.pas' {frmPersonelBilgileri},
  ufrmPersonelBilgisi in 'Forms\InputForms\ufrmPersonelBilgisi.pas' {frmPersonelBilgisi},
  Ths.Erp.Database.Table.AyarPersonelBolum in 'BackEnd\Ths.Erp.Database.Table.AyarPersonelBolum.pas',
  ufrmAyarPersonelBolumler in 'Forms\OutputForms\DbGrid\ufrmAyarPersonelBolumler.pas' {frmAyarPersonelBolumler},
  ufrmAyarPersonelBolum in 'Forms\InputForms\ufrmAyarPersonelBolum.pas' {frmAyarPersonelBolum},
  Ths.Erp.Database.Table.AyarPersonelBirim in 'BackEnd\Ths.Erp.Database.Table.AyarPersonelBirim.pas',
  ufrmAyarPersonelBirimler in 'Forms\OutputForms\DbGrid\ufrmAyarPersonelBirimler.pas' {frmAyarPersonelBirimler},
  ufrmAyarPersonelBirim in 'Forms\InputForms\ufrmAyarPersonelBirim.pas' {frmAyarPersonelBirim},
  Ths.Erp.Database.Table.AyarPersonelGorev in 'BackEnd\Ths.Erp.Database.Table.AyarPersonelGorev.pas',
  ufrmAyarPersonelGorevler in 'Forms\OutputForms\DbGrid\ufrmAyarPersonelGorevler.pas' {frmAyarPersonelGorevler},
  ufrmAyarPersonelGorev in 'Forms\InputForms\ufrmAyarPersonelGorev.pas' {frmAyarPersonelGorev},
  Ths.Erp.Database.Table.AyarVergiOrani in 'BackEnd\Ths.Erp.Database.Table.AyarVergiOrani.pas',
  ufrmAyarVergiOranlari in 'Forms\OutputForms\DbGrid\ufrmAyarVergiOranlari.pas' {frmAyarVergiOranlari},
  ufrmAyarVergiOrani in 'Forms\InputForms\ufrmAyarVergiOrani.pas' {frmAyarVergiOrani},
  Ths.Erp.Database.Table.BolgeTuru in 'BackEnd\Ths.Erp.Database.Table.BolgeTuru.pas',
  ufrmBolgeTurleri in 'Forms\OutputForms\DbGrid\ufrmBolgeTurleri.pas' {frmBolgeTurleri},
  ufrmBolgeTuru in 'Forms\InputForms\ufrmBolgeTuru.pas' {frmBolgeTuru},
  Ths.Erp.Database.Table.HesapGrubu in 'BackEnd\Ths.Erp.Database.Table.HesapGrubu.pas',
  ufrmHesapGruplari in 'Forms\OutputForms\DbGrid\ufrmHesapGruplari.pas' {frmHesapGruplari},
  ufrmHesapGrubu in 'Forms\InputForms\ufrmHesapGrubu.pas' {frmHesapGrubu},
  Ths.Erp.Database.Table.Ambar in 'BackEnd\Ths.Erp.Database.Table.Ambar.pas',
  ufrmAmbarlar in 'Forms\OutputForms\DbGrid\ufrmAmbarlar.pas' {frmAmbarlar},
  ufrmAmbar in 'Forms\InputForms\ufrmAmbar.pas',
  Ths.Erp.Database.Table.OlcuBirimi in 'BackEnd\Ths.Erp.Database.Table.OlcuBirimi.pas',
  ufrmOlcuBirimleri in 'Forms\OutputForms\DbGrid\ufrmOlcuBirimleri.pas' {frmOlcuBirimleri},
  ufrmOlcuBirimi in 'Forms\InputForms\ufrmOlcuBirimi.pas' {frmOlcuBirimi},
  Ths.Erp.Database.Table.UrunKabulRedNedeni in 'BackEnd\Ths.Erp.Database.Table.UrunKabulRedNedeni.pas',
  ufrmUrunKabulRedNedenleri in 'Forms\OutputForms\DbGrid\ufrmUrunKabulRedNedenleri.pas' {frmUrunKabulRedNedenleri},
  ufrmUrunKabulRedNedeni in 'Forms\InputForms\ufrmUrunKabulRedNedeni.pas' {frmUrunKabulRedNedeni},
  Ths.Erp.Database.Table.QualityFormMailReciever in 'BackEnd\Ths.Erp.Database.Table.QualityFormMailReciever.pas',
  ufrmQualityFormMailRecievers in 'Forms\OutputForms\DbGrid\ufrmQualityFormMailRecievers.pas' {frmQualityFormMailRecievers},
  ufrmQualityFormMailReciever in 'Forms\InputForms\ufrmQualityFormMailReciever.pas' {frmQualityFormMailReciever},
  Ths.Erp.Database.Table.SysUserMacAddressException in 'BackEnd\Ths.Erp.Database.Table.SysUserMacAddressException.pas',
  ufrmSysUserMacAddressExceptions in 'Forms\OutputForms\DbGrid\ufrmSysUserMacAddressExceptions.pas' {frmSysUserMacAddressExceptions},
  ufrmSysUserMacAddressException in 'Forms\InputForms\ufrmSysUserMacAddressException.pas' {frmSysUserMacAddressException},
  Ths.Erp.Database.Table.DovizKuru in 'BackEnd\Ths.Erp.Database.Table.DovizKuru.pas',
  ufrmDovizKurlari in 'Forms\OutputForms\DbGrid\ufrmDovizKurlari.pas' {frmDovizKurlari},
  ufrmDovizKuru in 'Forms\InputForms\ufrmDovizKuru.pas' {frmDovizKuru},
  Ths.Erp.Database.Table.Banka in 'BackEnd\Ths.Erp.Database.Table.Banka.pas',
  ufrmBankalar in 'Forms\OutputForms\DbGrid\ufrmBankalar.pas' {frmBankalar},
  ufrmBanka in 'Forms\InputForms\ufrmBanka.pas' {frmBanka},
  Ths.Erp.Database.Table.BankaSubesi in 'BackEnd\Ths.Erp.Database.Table.BankaSubesi.pas',
  ufrmBankaSubeleri in 'Forms\OutputForms\DbGrid\ufrmBankaSubeleri.pas' {frmBankaSubeleri},
  ufrmBankaSubesi in 'Forms\InputForms\ufrmBankaSubesi.pas' {frmBankaSubesi},
  Ths.Erp.Database.Table.SysMultiLangDataTableList in 'BackEnd\Ths.Erp.Database.Table.SysMultiLangDataTableList.pas',
  ufrmSysMultiLangDataTableLists in 'Forms\OutputForms\DbGrid\ufrmSysMultiLangDataTableLists.pas' {frmSysMultiLangDataTableLists},
  ufrmSysMultiLangDataTableList in 'Forms\InputForms\ufrmSysMultiLangDataTableList.pas' {frmSysMultiLangDataTableList},
  Ths.Erp.Database.Table.StokTipi in 'BackEnd\Ths.Erp.Database.Table.StokTipi.pas',
  ufrmStokTipleri in 'Forms\OutputForms\DbGrid\ufrmStokTipleri.pas' {frmStokTipleri},
  ufrmStokTipi in 'Forms\InputForms\ufrmStokTipi.pas' {frmStokTipi},
  Ths.Erp.Database.Table.CinsAilesi in 'BackEnd\Ths.Erp.Database.Table.CinsAilesi.pas',
  ufrmCinsAileleri in 'Forms\OutputForms\DbGrid\ufrmCinsAileleri.pas' {frmCinsAileleri},
  ufrmCinsAilesi in 'Forms\InputForms\ufrmCinsAilesi.pas' {frmCinsAilesi},
  Ths.Erp.Database.Table.CinsOzelligi in 'BackEnd\Ths.Erp.Database.Table.CinsOzelligi.pas',
  ufrmCinsOzellikleri in 'Forms\OutputForms\DbGrid\ufrmCinsOzellikleri.pas' {frmCinsOzellikleri},
  ufrmCinsOzelligi in 'Forms\InputForms\ufrmCinsOzelligi.pas' {frmCinsOzelligi},
  Ths.Erp.Database.Table.AyarHesapTipi in 'BackEnd\Ths.Erp.Database.Table.AyarHesapTipi.pas',
  ufrmAyarHesapTipleri in 'Forms\OutputForms\DbGrid\ufrmAyarHesapTipleri.pas' {frmAyarHesapTipleri},
  ufrmAyarHesapTipi in 'Forms\InputForms\ufrmAyarHesapTipi.pas' {frmAyarHesapTipi},
  Ths.Erp.Database.Table.StokKarti in 'BackEnd\Ths.Erp.Database.Table.StokKarti.pas',
  ufrmStokKartlari in 'Forms\OutputForms\DbGrid\ufrmStokKartlari.pas' {frmStokKartlari},
  ufrmStokKarti in 'Forms\InputForms\ufrmStokKarti.pas' {frmStokKarti},
  Ths.Erp.Database.Table.StokGrubuTuru in 'BackEnd\Ths.Erp.Database.Table.StokGrubuTuru.pas',
  ufrmStokGrubuTurleri in 'Forms\OutputForms\DbGrid\ufrmStokGrubuTurleri.pas' {frmStokGrubuTurleri},
  ufrmStokGrubuTuru in 'Forms\InputForms\ufrmStokGrubuTuru.pas' {frmStokGrubuTuru},
  Ths.Erp.Database.Table.StokGrubu in 'BackEnd\Ths.Erp.Database.Table.StokGrubu.pas',
  ufrmStokGruplari in 'Forms\OutputForms\DbGrid\ufrmStokGruplari.pas' {frmStokGruplari},
  ufrmStokGrubu in 'Forms\InputForms\ufrmStokGrubu.pas' {frmStokGrubu},
  ufrmBaseHelper in 'Forms\OutputForms\Helper\Factory\ufrmBaseHelper.pas' {frmBaseHelper},
  ufrmHelperOlcuBirimi in 'Forms\OutputForms\Helper\ufrmHelperOlcuBirimi.pas' {frmHelperOlcuBirimi},
  ufrmHelperStokGrubu in 'Forms\OutputForms\Helper\ufrmHelperStokGrubu.pas' {frmHelperStokGrubu},
  Ths.Erp.Database.Table.AyarBarkodUrunTuru in 'BackEnd\Ths.Erp.Database.Table.AyarBarkodUrunTuru.pas',
  ufrmAyarBarkodUrunTurleri in 'Forms\OutputForms\DbGrid\ufrmAyarBarkodUrunTurleri.pas' {frmAyarBarkodUrunTurleri},
  ufrmAyarBarkodUrunTuru in 'Forms\InputForms\ufrmAyarBarkodUrunTuru.pas' {frmAyarBarkodUrunTuru},
  Ths.Erp.Database.Table.AyarBarkodTezgah in 'BackEnd\Ths.Erp.Database.Table.AyarBarkodTezgah.pas',
  ufrmAyarBarkodTezgahlar in 'Forms\OutputForms\DbGrid\ufrmAyarBarkodTezgahlar.pas' {frmAyarBarkodTezgahlar},
  ufrmAyarBarkodTezgah in 'Forms\InputForms\ufrmAyarBarkodTezgah.pas' {frmAyarBarkodTezgah},
  Ths.Erp.Database.Table.AyarBarkodSeriNoTuru in 'BackEnd\Ths.Erp.Database.Table.AyarBarkodSeriNoTuru.pas',
  ufrmAyarBarkodSeriNoTurleri in 'Forms\OutputForms\DbGrid\ufrmAyarBarkodSeriNoTurleri.pas' {frmAyarBarkodSeriNoTurleri},
  ufrmAyarBarkodSeriNoTuru in 'Forms\InputForms\ufrmAyarBarkodSeriNoTuru.pas' {frmAyarBarkodSeriNoTuru},
  Ths.Erp.Database.Table.AyarBarkodHazirlikDosyaTuru in 'BackEnd\Ths.Erp.Database.Table.AyarBarkodHazirlikDosyaTuru.pas',
  ufrmAyarBarkodHazirlikDosyaTurleri in 'Forms\OutputForms\DbGrid\ufrmAyarBarkodHazirlikDosyaTurleri.pas' {frmAyarBarkodHazirlikDosyaTurleri},
  ufrmAyarBarkodHazirlikDosyaTuru in 'Forms\InputForms\ufrmAyarBarkodHazirlikDosyaTuru.pas' {frmAyarBarkodHazirlikDosyaTuru},
  Ths.Erp.Database.Table.AyarAskerlikDurumu in 'BackEnd\Ths.Erp.Database.Table.AyarAskerlikDurumu.pas',
  ufrmAyarAskerlikDurumlari in 'Forms\OutputForms\DbGrid\ufrmAyarAskerlikDurumlari.pas' {frmAyarAskerlikDurumlari},
  ufrmAyarAskerlikDurumu in 'Forms\InputForms\ufrmAyarAskerlikDurumu.pas' {frmAyarAskerlikDurumu},
  Ths.Erp.Database.Table.AyarCekSenetTipi in 'BackEnd\Ths.Erp.Database.Table.AyarCekSenetTipi.pas',
  ufrmAyarCekSenetTipleri in 'Forms\OutputForms\DbGrid\ufrmAyarCekSenetTipleri.pas' {frmAyarCekSenetTipleri},
  ufrmAyarCekSenetTipi in 'Forms\InputForms\ufrmAyarCekSenetTipi.pas' {frmAyarCekSenetTipi},
  Ths.Erp.Database.Table.AyarCekSenetCashEdiciTipi in 'BackEnd\Ths.Erp.Database.Table.AyarCekSenetCashEdiciTipi.pas',
  ufrmAyarCekSenetCashEdiciTipleri in 'Forms\OutputForms\DbGrid\ufrmAyarCekSenetCashEdiciTipleri.pas' {frmAyarCekSenetCashEdiciTipleri},
  ufrmAyarCekSenetCashEdiciTipi in 'Forms\InputForms\ufrmAyarCekSenetCashEdiciTipi.pas' {frmAyarCekSenetCashEdiciTipi},
  Ths.Erp.Database.Table.AyarCekSenetTahsilOdemeTipi in 'BackEnd\Ths.Erp.Database.Table.AyarCekSenetTahsilOdemeTipi.pas',
  ufrmAyarCekSenetTahsilOdemeTipleri in 'Forms\OutputForms\DbGrid\ufrmAyarCekSenetTahsilOdemeTipleri.pas' {frmAyarCekSenetTahsilOdemeTipleri},
  ufrmAyarCekSenetTahsilOdemeTipi in 'Forms\InputForms\ufrmAyarCekSenetTahsilOdemeTipi.pas' {frmAyarCekSenetTahsilOdemeTipi},
  ufrmHelperStokKarti in 'Forms\OutputForms\Helper\ufrmHelperStokKarti.pas' {frmHelperStokKarti};

{$R *.res}

begin
  Application.Initialize;

  ReportMemoryLeaksOnShutdown := True;

  Application.Title := 'Thunder Soft ERP';
  Application.CreateForm(TfrmMain, frmMain);
  if TfrmLogin.Execute then
  begin
    Application.ShowMainForm := True;
    Application.Run;
  end
  else
  begin
    Application.Terminate;
  end;
end.

