unit Ths.Erp.Constants;

interface

const
  SURUM = 'A';

  EPSILON          = 0.00009;
  EPSILON_ISLEMLER = 0.009;//2 haneye bakýlýr

  IMG_ACCEPT = 0;
  IMG_ADD = 1;
  IMG_APPLICATION = 2;
  IMG_ARCHIVE = 3;
  IMG_ATTACHMENT = 4;
  IMG_BACK = 5;
  IMG_CALCULATOR = 6;
  IMG_CALENDAR = 7;
  IMG_CHART = 8;
  IMG_CLOCK = 9;
  IMG_COMMENT = 10;
  IMG_COMMUNITY_USERS = 11;
  IMG_COMPUTER = 12;
  IMG_COMPUTERS = 13;
  IMG_DATABASE = 14;
  IMG_DOWN = 15;
  IMG_EJECT = 16;
  IMG_EXCEL = 17;
  IMG_FAVORITE = 18;
  IMG_FOLDER = 19;
  IMG_FORWARD_NEW_MAIL = 20;
  IMG_HELP = 21;
  IMG_HOME = 22;
  IMG_IMAGE = 23;
  IMG_INFO = 24;
  IMG_LOCK = 25;
  IMG_LOCK_DISABLED = 26;
  IMG_LOCK_OFF = 27;
  IMG_LOCK_OFF_DISABLED = 28;
  IMG_MAIL = 29;
  IMG_MOVIE = 30;
  IMG_NEXT = 31;
  IMG_NOTE = 32;
  IMG_PAGE = 33;
  IMG_PAGE_SEARCH = 34;
  IMG_PAUSE = 35;
  IMG_PDF = 36;
  IMG_PLAY = 37;
  IMG_PRINTER = 38;
  IMG_PRINTER_SEARCH = 39;
  IMG_PROCESS = 40;
  IMG_RECORD = 41;
  IMG_REMOVE = 42;
  IMG_REPEAT = 43;
  IMG_REWIND = 44;
  IMG_RSS = 45;
  IMG_SEARCH = 46;
  IMG_USER_SHE = 47;
  IMG_SHOPING_CART = 48;
  IMG_SKIP_BACKWARD = 49;
  IMG_SKIP_FORWARD = 50;
  IMG_SUM = 51;
  IMG_UP = 52;
  IMG_USER_HE = 53;
  IMG_USER_COMMENTS = 54;
  IMG_USERS = 55;
  IMG_VIDEO = 56;
  IMG_WARNING = 57;
  IMG_WINDOW = 58;
  IMG_WORD = 59;

  STATUS_SQL_SERVER   = 0;
  STATUS_DATE         = 1;
  STATUS_EX_RATE_USD  = 2;
  STATUS_EX_RATE_EUR  = 3;
  STATUS_USERNAME     = 4;
  STATUS_KEY_F4       = 5;
  STATUS_KEY_F5       = 6;
  STATUS_KEY_F6       = 7;
  STATUS_KEY_F7       = 8;

  SQL_PARAM_SEPERATE = ':';

implementation

end.
